version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: smart_door_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: smart_door_lock
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_kamu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: smart_door_mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
